# Site settings
title: Ryan Daigle
description: >
    Locally sourced, organic, artisinal bits. Engineering at Spreedly. Elixir enthusiast.
author: Ryan Daigle
email: ryan.daigle@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ryandaigle.com" # the base hostname & protocol for your site
twitter_username: rwdaigle
github_username: rwdaigle

# Build settings
include: ["a"]
markdown: kramdown
permalink: /:title
sass:
    style: compressed
